import{j as e}from"./index.js";import{w as a,a as r,e as s,b as l,c as o,f as x,d as n,i as p,g as c,l as i}from"./Footer.js";function h({light:t,top:d,useLang:m}){return e.jsx("section",{dir:"ltr",className:`hidden md:block bounce2 absolute z-10 ${d} -left-[55px]`,children:e.jsx("div",{className:"items-center gap-6 !rotate-[-90deg] md:flex",children:e.jsxs("div",{className:"flex items-center justify-center gap-2",children:[e.jsxs("a",{target:"_blank",href:"https://wa.me/971508936752",className:`relative transition-all rotate-[90deg] p-2 border ${t?"border-white":"border-[#D9D9D9]"} rounded-full flex items-center justify-center w-[36px] h-[36px] 2xl:w-[45px] 2xl:h-[45px] group`,children:[e.jsx("img",{src:t?a:r,alt:"",className:"2xl:w-[45px]"}),e.jsxs("span",{className:`absolute left-[176%] text-center -translate-x-[41%] top-2/2 -translate-y-2/2 
              bg-[#46D287] text-white text-xs py-[13px] px-[11px] rounded-full opacity-0 
              group-hover:opacity-100 transition-all duration-1000 
              whitespace-nowrap flex items-center gap-2 w-0 group-hover:w-[150px]`,children:[e.jsx("img",{src:t?a:r,alt:"",className:"2xl:w-[45px]"}),"+971508936752"]})]}),e.jsxs("a",{target:"_blank",href:"mailto:info@oonatech.com",className:`relative transition-all rotate-[90deg] p-2 border ${t?"border-white":"border-[#D9D9D9]"} rounded-full flex items-center justify-center w-[36px] h-[36px] 2xl:w-[45px] 2xl:h-[45px] group`,children:[e.jsx("img",{src:t?s:l,alt:"",className:"2xl:w-[45px]"}),e.jsxs("span",{className:`absolute left-[176%] text-center -translate-x-[41%] top-2/2 -translate-y-2/2 
               bg-[#9563FF] text-white text-xs py-[13px] px-[11px] rounded-full opacity-0 
               group-hover:opacity-100 transition-all duration-1000 
               whitespace-nowrap flex items-center gap-2 w-0 group-hover:w-[150px]`,children:[e.jsx("img",{src:t?s:l,alt:"",className:"2xl:w-[45px]"})," ","info@oonatech.com"]})]}),e.jsxs("a",{target:"_blank",href:"https://www.facebook.com/oonatech",className:`relative transition-all rotate-[90deg] p-2 border ${t?"border-white":"border-[#D9D9D9]"} rounded-full flex items-center justify-center w-[36px] h-[36px] 2xl:w-[45px] 2xl:h-[45px] group`,children:[e.jsx("img",{src:t?o:x,alt:"",className:"2xl:w-[20px]"}),e.jsxs("span",{className:`absolute left-[176%] text-center -translate-x-[41%] top-2/2 -translate-y-2/2 
               bg-[#00A7E1] text-white text-xs p-[11px] rounded-full opacity-0 
               group-hover:opacity-100 transition-all duration-1000 
               whitespace-nowrap flex items-center gap-2 w-0 group-hover:w-[150px]`,children:[e.jsx("img",{src:t?o:x,alt:"",className:"2xl:w-[20px]"}),"@oonatech"]})]}),e.jsxs("a",{target:"_blank",href:"https://www.instagram.com/oonatech/",className:`relative transition-all rotate-[90deg] p-2 border ${t?"border-white":"border-[#D9D9D9]"} rounded-full flex items-center justify-center w-[36px] h-[36px] 2xl:w-[45px] 2xl:h-[45px] group`,children:[e.jsx("img",{src:t?n:p,alt:"",className:"2xl:w-[45px]"}),e.jsxs("span",{className:`absolute left-[176%] text-center -translate-x-[41%] top-2/2 -translate-y-2/2 
               bg-[#FF5F5F] text-white text-xs p-[11px] rounded-full opacity-0 
               group-hover:opacity-100 transition-all duration-1000 
               whitespace-nowrap flex items-center gap-2 w-0 group-hover:w-[150px]`,children:[e.jsx("img",{src:t?n:p,alt:"",className:"2xl:w-[45px]"}),"@oonatech"]})]}),e.jsxs("a",{target:"_blank",href:"https://www.linkedin.com/company/oona-tech",className:`relative transition-all rotate-[90deg] p-2 border ${t?"border-white":"border-[#D9D9D9]"} rounded-full flex items-center justify-center w-[36px] h-[36px] 2xl:w-[45px] 2xl:h-[45px] group`,children:[e.jsx("img",{src:t?c:i,alt:"",className:"2xl:w-[20px]"}),e.jsxs("span",{className:`absolute left-[176%] text-center -translate-x-[41%] top-2/2 -translate-y-2/2 
               bg-[#253368] text-white text-xs p-[11px] rounded-full opacity-0 
               group-hover:opacity-100 transition-all duration-1000 
               whitespace-nowrap flex items-center gap-2 w-0 group-hover:w-[150px]`,children:[e.jsx("img",{src:t?c:i,alt:"",className:"2xl:w-[20px]"}),"@oona-tech"]})]})]})})})}export{h as C};
